# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [323]:
import numpy as np


array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.69118787e-306,
       7.56587585e-307, 1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
       1.42421160e-306, 8.34446411e-308])

3. Create a vector with values ranging from 10 to 49

In [3]:
import numpy as np
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
import numpy as np
a = np.arange(10,50)
a
a.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
import numpy as np
a = np.arange(10,50)
a
type(a)

numpy.ndarray

6. Print the numpy version and the configuration


In [ ]:
a = np.version

7. Print the dimension of the array in question 3


In [6]:
import numpy as np
a = np.arange(10,50)
a
a.ndim

1

8. Create a boolean array with all the True values

In [52]:
import numpy as np
a = np.arange(5)
a <5





array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [36]:
import numpy as np
c = np.ndarray([2,2])
c


array([[1.05807491e-311, 2.78146116e-307],
       [1.61324900e-307, 3.56043053e-307]])

10. Create a three dimensional array



In [48]:
import numpy as np
d = np.ndarray([3,1,1])
d

array([[[7.74860419e-304]],

       [[7.74860419e-304]],

       [[7.74860419e-304]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [32]:
import numpy as np
a = np.arange(10,0,-1)
print(a)


[10  9  8  7  6  5  4  3  2  1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [48]:
import numpy as np
g= np.zeros(10)
g[4]=1
g



array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [61]:
import numpy as np
d = np.zeros([3,3])
d[0,0]=1
d[2,2]=1
d[1,1]=1
d


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [22]:
no able to complete 

TypeError: 'numpy.dtype' object is not callable

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [155]:
import numpy as np
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [80]:
arr3= (arr1)==(arr2)
arr3

array([[ True,  True,  True],
       [ True,  True,  True]])

17. Extract all odd numbers from arr with values(0-9)

In [137]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [122]:
a=np.arange(1,10,2)
a[:]=1
a


array([1, 1, 1, 1, 1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [131]:
arr
arr[5]=12
arr[6]=12
arr[7]=12
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [278]:
import numpy as np
arr = np.zeros([3,3])
arr[0]=1
arr[1]=1
arr[1,1]=0
arr[2]=1
arr

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [279]:
import numpy as np
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [282]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [332]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b=a[0]
b





array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [333]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b=a[1]
b


array([3, 4, 5])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [342]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b=a[0:2,2]
b

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [138]:
np.ndarray([10,10])


array([[8.12407844e-312, 8.12374679e-312, 8.12410270e-312,
        8.12405770e-312, 8.12407844e-312, 8.12410336e-312,
        8.12407844e-312, 8.12407844e-312, 8.12407844e-312,
        8.12414329e-312],
       [8.12407844e-312, 8.12407844e-312, 8.12407844e-312,
        8.12407845e-312, 8.12410329e-312, 8.12407845e-312,
        8.12407845e-312, 8.12414329e-312, 8.12410336e-312,
        8.12407845e-312],
       [8.12407845e-312, 8.12414329e-312, 8.12410336e-312,
        8.12407845e-312, 8.12407845e-312, 8.12414329e-312,
        8.12414329e-312, 8.12410336e-312, 8.12407845e-312,
        8.12414329e-312],
       [8.12407845e-312, 8.12407845e-312, 8.12407845e-312,
        8.12410329e-312, 8.12407845e-312, 8.12414330e-312,
        8.12407845e-312, 8.12407845e-312, 8.12407845e-312,
        8.12410270e-312],
       [8.12407845e-312, 8.12407845e-312, 8.12410329e-312,
        8.12407845e-312, 8.12407845e-312, 8.12407845e-312,
        8.12414330e-312, 8.12410336e-312, 8.12407845e-312,
        8.1

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [148]:
not able to complete 



NameError: name 'b' is not defined

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [388]:
not able to complete 

array([2, 5])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [ ]:
not able to complete 

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
not able to complete 

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [181]:
np.arange(1,16).reshape(5,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [228]:
np.arange(1,17).reshape(8,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

33. Swap axes of the array you created in Question 32

In [238]:
not able to complete

ValueError: cannot reshape array of size 1 into shape (2,)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [252]:
np.arange(10).reshape(2,5)*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [259]:
not able to complete


TypeError: 'module' object is not callable

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [269]:
not able to complete

SyntaxError: invalid syntax (<ipython-input-269-72562759733a>, line 1)

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [262]:
not able to complete 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
not able to complete 

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
not able to complete

40. Generate a matrix of 20 random values and find its cumulative sum

In [268]:
not able to complete 

SyntaxError: invalid syntax (<ipython-input-268-4131a3e8f86c>, line 1)

In [ ]:
not able to complete 